# Pre-commit hooks for H2K-HPXML project
# Simple, reliable configuration focusing on essential code quality
# See https://pre-commit.com for more information

repos:
  # Built-in hooks for file consistency
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/fixtures/
      - id: end-of-file-fixer
        exclude: ^tests/fixtures/
      - id: check-yaml
        exclude: ^tests/fixtures/
      - id: check-toml
      - id: check-json
        exclude: ^(tests/fixtures/|\.devcontainer/)
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: mixed-line-ending
        args: ['--fix=lf']
        exclude: ^tests/fixtures/

  # Python code formatting with Black
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        exclude: ^tests/fixtures/

# Configuration for individual repositories
default_language_version:
  python: python3

# Global exclusions (in addition to repo-specific ones)
exclude: |
  (?x)^(
    tests/fixtures/.*|
    tests/archived_tests/.*|
    .*\.xml|
    .*\.h2k|
    .*\.hpxml|
    .*\.epw
  )$

# Note: Ruff and MyPy can be run manually for development:
# ruff check src/ tests/
# mypy src/h2k_hpxml/core/
