name: Build and Push Docker Image to Docker Hub

# This workflow runs on every push to any branch.
on:
  push:
    branches:
      - '**' # Matches every branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract branch name
        id: extract_branch
        run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Tags the image with the branch name. e.g., canmet-energy/h2k-hpxml:my-feature-branch
          # If the branch is 'main', it also adds the 'latest' tag.
          tags: |
            canmet-energy/h2k-hpxml:${{ steps.extract_branch.outputs.branch_name }}
            ${{ github.ref == 'refs/heads/main' && 'canmet-energy/h2k-hpxml:latest' || '' }}